// export interface TerminalInfo {
//   [key: string]: string | null
// }

export interface TerminalInfoTs
{
    terminalId: string | null,
    terminalSn: string | null,
    terminalVer: string | null,
    merchantName: string | null,
    presentName: string | null,
    tel: string | null,
    address: string | null,
    addressDetail: string | null,
    businessNo: string | null,
    bizType: string | null,
    presentRegNo: string | null,
    merchantType: string | null,
    connectCode: string | null,
    securityLevel: string | null,
    groupCode: string | null,
    saleType: string | null,
    dnsFlag: string | null,
    stateFlag: string | null,
    useFlag: string | null,
    enableServiceList: string | null,
    lastDnLdDate: string | null,
    lastDnLdTime: string | null,
    lastAdjustReqDate: string | null,
    temp: string | null,
    categoryCode: string | null,
    agentCode: string | null,
    vanTerminalId: string | null,
    orgTerminalId1: string | null,
    orgTerminalId2: string | null,
    orgTerminalId3: string | null,
    pgMerchNbr: string | null,
    vanCode: string | null,
    procId: string | null,
    afterData: string | null,
    newTerminalId: string | null,
    code: string | null,
    organizationPath: string | null,
    model: string | null,
    modem: string | null,
    modemSN: string | null,
    modemInfo: string | null,
    place: string | null,
    transactionNo: string | null,
    isSoldOut: string | null,
    isControlError: string | null,
    isPdError: string | null,
    isEmptyCol: string | null,
    company: string | null,
    userName: string | null,
    userId: string | null,
    aspCharge: string | null,
    placeCode: string | null,
    placeNo: string | null,
    accessStatus: string | null,
    organ: string | null,
    controlError: string | null,
    pdError: string | null,
    isExpire: string | null,
    emptyCol: string | null,
    soldOut: string | null,
    tranDate: string | null,
    tranDate2: string | null,
    finalTranDate: string | null,
    isTradeIn: string | null,
    csMemo: string | null,
    memo: string | null,
    tmsFlag: string | null,
    cardId: string | null,
    responseDate: string | null,
    resCode: string | null
}


// export interface TerminalInfo {
//     terminalId:string,
//     terminalSn:string,
//     terminalVer:string,
//     merchantName:string,
//     presentName:string,
//     tel:string,
//     address:string,
//     addressDetail:string,
//     businessNo:string,
//     bizType:string,
//     presentRegNo:string,
//     merchantType:string,
//     connectCode:string,
//     securityLevel:string,
//     groupCode:string,
//     saleType:string,
//     dnsFlag:string,
//     stateFlag:string,
//     useFlag:string,
//     enableServiceList:string,
//     lastDnLdDate:string,
//     lastDnLdTime:string,
//     lastAdjustReqDate:string,
//     temp:string,
//     categoryCode:string,
//     agentCode:string,
//     vanTerminalId:string,
//     orgTerminalId1:string,
//     orgTerminalId2:string,
//     orgTerminalId3:string,
//     pgMerchNbr:string,
//     vanCode:string,
//     procId:string,
//     afterData:string,
//     newTerminalId:string,
//     code:string,
//     organizationPath:string,
//     model:string,
//     modem:string,
//     modemSN:string,
//     modemInfo:string,
//     place:string,
//     transactionNo:string,
//     isSoldOut:string,
//     isControlError:string,
//     isPdError:string,
//     isEmptyCol:string,
//     company:string,
//     userName:string,
//     userId:string,
//     aspCharge:string,
//     placeCode:string,
//     placeNo:string,
//     accessStatus:string,
//     organ:string,
//     controlError:string,
//     pdError:string,
//     isExpire:string,
//     emptyCol:string,
//     soldOut:string,
//     tranDate:string,
//     tranDate2:string,
//     finalTranDate:string,
//     isTradeIn:string,
//     csMemo:string,
//     memo:string,
//     tmsFlag:string,
//     cardId:string,
//     responseDate:string,
//     resCode: string
// }
